### ISSUE TITLE
Read<T> return warning and null values

### ISSUE THREAD

**Issue by NTTLuke** [Chatham/Vault.NET#26]
Hi 
I have downloaded latest version of Vault yesterday.
I have an issue with the Read method.

The method 

```
var key= "cn";
var path = "secret/mongodb";
var result = await _client.Secret.Read<Dictionary<string, string>>(path);
return result?.Data?[key];
```

returns
- result with this warning 

> Invalid path for a versioned K/V secrets engine. See the API docs for the appropriate API endpoints to use. If using the Vault CLI, use 'vault kv get' for this operation.

- and the result?.Data is null

**Other info**

- Using  the Vault client with the same user and password , for having the properly token , works fine. 

- Looking inside the UI , the secret version is v2 but during the debug the client.Secret seems v1. Is it possible ?

Do you have suggestions ? 
Thank you

**Comment by chrishoffman** [comment]
There are different api paths for the v2 api. You need to request your data at ‘secret/data/mongodb’ in kv v2.

**Comment by NTTLuke** [comment]
Hi Chris thank you 
I missed that I have already changed the path using "secret/data/mongodb" and I received this error

> One or more errors occurred. (Unexpected character encountered while parsing value: {. Path 'data.data', line 1, position 120.)

Thank you

**Comment by chrishoffman** [comment]
The data type returned by KVv2 is not `Dictionary<String, String>`, it is `Dictionary<String, Dictionary<String, String>>`.  I created some tests to test KVv2 behavior to show usage.

https://github.com/Chatham/Vault.NET/pull/27

**Comment by apuchkov** [comment]
I think it worth adding a sample in a readme to show how to get secrets from kv2.

I just tried to use this library for the first time following the readme and ran into the same two problems:
 - having a path without a "data" in it (StackOverflow helped with that)
 - then getting exception "Unexpected character encountered while parsing value: {. Path 'data.data', line 1, position 120.)" (luckily found this ticket after going through issues one be one)
