### ISSUE TITLE
bug in SealStatus

### ISSUE THREAD

**Issue by dimula** [Chatham/Vault.NET#7]
Instead of:
    return _client.Get<SealStatusResponse>($"${UriPathBase}/seal-status", ct);
should be
    return _client.Get<SealStatusResponse>($"{UriPathBase}/seal-status", ct);

**Comment by dimula** [comment]
and exception also very unpleasant: "Unexpected content media type text/plain"

**Comment by grounded042** [comment]
should be good now. thanks for letting us know @dimula
